name       : perl-xml-namespacesupport
version    : 1.11
release    : 5
source     :
    - http://search.cpan.org/CPAN/authors/id/P/PE/PERIGRIN/XML-NamespaceSupport-1.11.tar.gz : 6d8151f0a3f102313d76b64bfd1c2d9ed46bfe63a16f038e7d860fda287b74ea
license    :
    - Artistic-Perl-1.0
summary    : XML::NameSpaceSupport - a simple generic namespace support class
component  : programming.perl
description: |
    XML::NameSpaceSupport - a simple generic namespace support class
setup      : |
    export PERL_USE_UNSAFE_INC=1
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
