name       : perl-xml-namespacesupport
version    : '1.12'
release    : 8
source     :
    - https://cpan.metacpan.org/authors/id/P/PE/PERIGRIN/XML-NamespaceSupport-1.12.tar.gz : 47e995859f8dd0413aa3f22d350c4a62da652e854267aa0586ae544ae2bae5ef
license    :
    - Artistic-Perl-1.0
summary    : XML::NameSpaceSupport - a simple generic namespace support class
component  : programming.perl
description: |
    XML::NameSpaceSupport - a simple generic namespace support class
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
